import { useEffect, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import Screen from "../components/Screen"; import AppButton from "../components/AppButton";
import { api } from "../services/api"; import { useSession } from "../context/SessionContext"; import { getLevel } from "../config/levels"; import { colors } from "../theme/colors";

export default function ResultScreen({ route, navigation }) {
  const { levelId, score, correctAnswers, totalQuestions, maxScore } = route.params; const { session } = useSession(); const level = getLevel(levelId); const [status, setStatus] = useState("saving"); const [message, setMessage] = useState("");
  useEffect(() => { let active = true; api.submitScore({ levelId, score, correctAnswers, totalQuestions }, session.token).then((data) => { if (active) { setStatus("saved"); setMessage(data.isPersonalBest ? "Kỷ lục cá nhân mới!" : "Kết quả đã được lưu."); } }).catch((err) => { if (active) { setStatus("error"); setMessage(err.message); } }); return () => { active = false; }; }, [correctAnswers, levelId, score, session.token, totalQuestions]);
  const percent = Math.round((score / maxScore) * 100); const title = percent >= 80 ? "Xuất sắc!" : percent >= 50 ? "Làm tốt lắm!" : "Thử lại nhé!";
  return <Screen contentStyle={styles.screen}><View style={styles.confetti}><Text style={styles.emoji}>{percent >= 80 ? "🏆" : percent >= 50 ? "🎉" : "🧭"}</Text><Text style={styles.title}>{title}</Text><Text style={[styles.level, { color: level.color }]}>{level.icon} Cấp độ {level.name}</Text></View>
    <View style={styles.card}><Text style={styles.score}>{score}</Text><Text style={styles.label}>ĐIỂM</Text><View style={styles.divider} /><View style={styles.row}><View style={styles.stat}><Text style={styles.statValue}>{correctAnswers}/{totalQuestions}</Text><Text style={styles.statLabel}>Câu đúng</Text></View><View style={styles.stat}><Text style={styles.statValue}>{percent}%</Text><Text style={styles.statLabel}>Hiệu suất</Text></View></View></View>
    <View style={styles.status}>{status === "saving" && <ActivityIndicator color={colors.accent} />}<Text style={[styles.statusText, status === "error" && styles.error]}>{status === "saving" ? "Đang lưu kết quả…" : message}</Text></View>
    <View style={styles.actions}><AppButton title="Chơi lại" onPress={() => navigation.replace("Quiz", { levelId })} /><AppButton title="Xem bảng xếp hạng" variant="secondary" onPress={() => navigation.navigate("Leaderboard", { initialLevel: levelId })} /><AppButton title="Về trang chính" variant="ghost" onPress={() => navigation.popTo("Home")} /></View>
  </Screen>;
}
const styles = StyleSheet.create({ screen: { gap: 18, justifyContent: "center" }, confetti: { alignItems: "center" }, emoji: { fontSize: 62 }, title: { color: colors.text, fontSize: 34, fontWeight: "900", marginTop: 8 }, level: { fontWeight: "800", marginTop: 6 }, card: { backgroundColor: colors.surface, borderRadius: 26, borderWidth: 1, borderColor: colors.border, padding: 24, alignItems: "center" }, score: { color: colors.accent, fontWeight: "900", fontSize: 54 }, label: { color: colors.muted, fontWeight: "800", letterSpacing: 2 }, divider: { width: "100%", height: 1, backgroundColor: colors.border, marginVertical: 20 }, row: { flexDirection: "row", width: "100%" }, stat: { flex: 1, alignItems: "center" }, statValue: { color: colors.text, fontSize: 22, fontWeight: "900" }, statLabel: { color: colors.muted, marginTop: 4 }, status: { minHeight: 24, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8 }, statusText: { color: colors.muted, textAlign: "center" }, error: { color: colors.danger }, actions: { gap: 10 } });
